variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: millerk97
  APP_NAME: ase
  REPO: vu-advanced-software-engineering/students/2021s/ASE_Team_0105

stages:
  - build
  - docker

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script: 
    - mvn -f implementation/txhistory/pom.xml clean package
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:19.03.12
  stage: docker
  tags:
    - swa
  services:
    - docker:19.03.12-dind
  script:
    - docker build -f implementation/txhistory/Dockerfile -t txhistory-docker .
