    image: node:latest

    stages:
      - build
      - test
      - release

    cache:
      paths:
        - implementation/cart/container/node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
        - implementation/cart/container/node_modules/

    cart_testing:
      stage: test
      artifacts:
        paths:
        - implementation/cart/container/
      script: 
        - cd implementation/cart/container
        - npm install -g mocha
        - npm install
        - nohup npm start &
        - npm run test

    release_upload:
      image: registry.gitlab.com/gitlab-org/release-cli:v0.1.0
      script:
        - release-cli create --name="My Release" --description="My Release description"