image: gitlab/dind
services:
  - docker:dind

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: 
    - mvn -f implementation/txhistory/pom.xml clean package
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - docker build -f implementation/txhistory/Dockerfile -t txhistory-docker .
