image: gitlab/dind
services:
  - docker:dind


variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: millerk97
  APP_NAME: springbootgitlab
  REPO: vu-advanced-software-engineering/students/2021s/ASE_Team_0105

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script: 
    - mvn -f implementation/txhistory/pom.xml clean package
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f implementation/txhistory/Dockerfile -t txhistory-docker .
