
stages:
  - build
  - test
  - integrationTest
  - release
  - cleanup

build:
  stage: build
  image: maven:3-openjdk-11
  script: 
#    - mvn -f implementation/shipment/pom.xml package 
    - mvn -f implementation/checkout/pom.xml package -Pconf -Ddir=../../deployment
    - cd deployment
    - ls
  artifacts:
    paths:
    - deployment/*.jar



AccessCheck:
  stage: test
  image: docker:latest
  script:
    - cd deployment
    - ls  




release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: integration_test
      artifacts: true
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  artifacts:
    paths:
      - deployment
  script:
    - cd deployment
    - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA

