    image: node:latest

    stages:
      - build
      - test

    cache:
      paths:
        - implementation/cart/container/node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
        - implementation/cart/container/node_modules/

    cart_testing:
      stage: test
      
      artifacts:
        paths:
        - implementation/cart/container/
      script: 
        - cd implementation/cart/container
        - npm install
        - npm run test