stages:
  - integrationTest
 # - build
 # - deploy
 # - docker

#maven-build:
#  image: maven:3-openjdk-11
#  stage: build
#  tags:
#    - swa
#  script: 
#    - mvn -f implementation/txhistory/pom.xml compile com.google.cloud.tools:jib-maven-plugin:2.3.0:dockerBuild
#  artifacts:
#    paths:
#      - deployment/txhistory-0.0.1-SNAPSHOT.jar

#deploy:
#  image: maven:3-openjdk-11
#  stage: deploy
#  script:
#    - mvn deploy -s ci_settings.xml
#  only:
#    - master

#deploy:
#  image: maven:3-openjdk-11
#  stage: deploy
#  tags:
#    - swa
#  script:
#    - mvn deploy -s ci_settings.xml
#  only:
#    - master

#docker-build:
#  image: docker:19.03.12
#  stage: docker
#  tags:
#    - swa
#  services:
 #   - docker:19.03.12-dind
#  script:
#    - docker build -f implementation/txhistory/Dockerfile -t txhistory-docker .



integration_test:
  image: ubuntu:latest
  stage: integrationTest
  artifacts:
    paths:
      - implementation/cart/container/
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive 
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime 
    - echo $TZ > /etc/timezone
#install and run Java things here
    - apt -y install nodejs npm 
    - cd implementation/cart/container
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test
    - apt-get -y install default-jre-headless
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*
    - cd ../../../deployment/
    - java -jar checkout-0.0.1.jar &
