

    stages:
      - build
      - test
      - integrationTest
      - release

#    cache:
#      paths:
 #       - implementation/cart/container/node_modules/
#
 #   install_dependencies:
  ##    stage: build
    #  script:
     #   - npm install
      #artifacts:
       # paths:
        #- implementation/cart/container/node_modules/

    cart_start:
      image: node:latest
      stage: test
      artifacts:
        paths:
        - implementation/cart/container/
      script: 
        - cd implementation/cart/container
        - npm install
        - npm start





    cart_testing:
      services:
        - name: node:latest
          alias: app
          command: ["cd implementation/cart/container, npm start"]
      image: node:latest      
      stage: test
#      environment:
#        - GATEWAYIP=$CI_SERVER_HOST
#        - GATEWAYIP : '$CI_SERVER_HOST'
      variables:
        GATEWAYIP: $app
      artifacts:
        paths:
        - implementation/cart/container/
      script: 
        - cd implementation/cart/container
        - npm install -g mocha
        - npm install
        - npm run test

    integration_test:
        image: node:latest
        stage: integrationTest
        artifacts:
          paths:
          - implementation/test
        needs:
          - job: cart_testing
            artifacts: true
        script: 
        - cd implementation/test
        - npm install -g mocha
        - npm install
        - mocha endToEndTest.js --exit

    release_upload:
      stage: release
      image: registry.gitlab.com/gitlab-org/release-cli:latest
      needs:
        - job: integration_test
          artifacts: true
      rules:
        - if: '$RELEASE == "True"'
        - if: '$CI_COMMIT_BRANCH == "master"'

      script:
        - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA