
stages:
  - build
  - test
  - integrationTest
  - release
  - cleanup

build:
  stage: build
  image: maven:3-openjdk-11
  script: 
    - mvn -f implementation/shipment/pom.xml package 
    - mvn -f implementation/checkout/pom.xml package -Pconf -Ddir=../../deployment/checkout
    - cd ../../deployment/checkout
    - ls
  artifacts:
    paths:
    - ../../deployment/checkout/*.jar



AccessCheck:
  stage: test
  image: docker:latest
  script:
    - cd deployment
    - ls  


cart_testing:
  #services:
    #- name: node:latest
      #alias: app
  image: node:latest
  stage: test
  artifacts:
    paths:
      - implementation/cart/container/
  script:
    - cd implementation/cart/container
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test

## add services to test


integration_test:
  image: ubuntu:latest
  stage: integrationTest
  artifacts:
    paths:
      - implementation/cart/container/
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive 
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime 
    - echo $TZ > /etc/timezone
#install and run Java things here
    - apt -y install nodejs npm 
    - cd implementation/cart/container
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test
    - apt-get -y install default-jre-headless
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*
    - cd ../../checkout/target
    - java -jar checkout-0.0.1-SNAPSHOT.jar &



release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: integration_test
      artifacts: true
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'

  script:
    - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA

