
stages:
  - build
  - test
  - integrationTest
  - release
  - cleanup




create:
  stage: build
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "${CI_JOB_ID}" > CI_JOB_ID.txt
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
    - ls
  artifacts:
    paths:
      - deployment
    reports:
       dotenv: job.env  



release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: create
      artifacts: true
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - echo $JOB_ID
#    - cd deployment
    - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID 
      --assets-link "{\"name\":\"Microservices\",\"url\":\"https://git01lab.cs.univie.ac.at/vu-advanced-software-engineering/students/2021s/ASE_Team_0105/-/jobs/`cat $JOB_ID `/artifacts/download\"}"

