


stages:
  - build
  - unitTest
  - integrationTest
  - release


maven_build:
  image: maven:3-openjdk-11
  stage: build
  tags:
    - swa
  script: 
    - mvn -f implementation/shipment/pom.xml package 
    - mvn -f implementation/checkout/pom.xml package 
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
    - cd deployment
    - ls
  artifacts:
    paths:
      - implementation/*
    reports:
       dotenv: job.env  


#cart_testing:
  #services:
    #- name: node:latest
      #alias: app
#  image: node:latest
#  stage: unitTest
#  artifacts:
#    paths:
#      - implementation/cart/container/
#  script:
#    - cd implementation/cart/container
#    - npm start --host=app &
#    - npm install -g mocha
#    - npm install
#    - npm run test

integration_test:  
  tags:
    - swa
  image: ubuntu:latest
  stage: integrationTest
  needs:
    - job: maven_build
      artifacts: true
  artifacts:
     paths: 
       - implementation
  script:
    - ls
    - cd implementation/checkout/target
    - ls
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive 
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime 
    - echo $TZ > /etc/timezone
#install and run Java things here
    - apt -y install nodejs npm 
    - cd ../../cart/container
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test

    - apt-get -y install default-jre-headless
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*
    - cd ../../
    - ls
    - java -jar checkout/target/checkout-2.4.4.jar


release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: maven_build
      artifacts: true
    - job: integration_test
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
#    - cd deployment
    - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID 
      --assets-link "{\"name\":\"Microservices\",\"url\":\"https://git01lab.cs.univie.ac.at/vu-advanced-software-engineering/students/2021s/ASE_Team_0105/-/jobs/$JOB_ID/artifacts/download\"}"

