stages:
 # - build
  - deploy
 # - docker

#maven-build:
#  image: maven:3-openjdk-11
#  stage: build
#  tags:
#    - swa
#  script: 
#    - mvn -f implementation/txhistory/pom.xml compile com.google.cloud.tools:jib-maven-plugin:2.3.0:dockerBuild
#  artifacts:
#    paths:
#      - deployment/txhistory-0.0.1-SNAPSHOT.jar

#deploy:
#  image: maven:3-openjdk-11
#  stage: deploy
#  script:
#    - mvn deploy -s ci_settings.xml
#  only:
#    - master

deploy:
  image: maven:3-openjdk-11
  stage: deploy
  script:
    #- mvn deploy -s ci_settings.xml
    - echo ${env.CI_SERVER_URL}
    - echo ${env.CI_PROJECT_ID}
  only:
    - master

#docker-build:
#  image: docker:19.03.12
#  stage: docker
#  tags:
#    - swa
#  services:
 #   - docker:19.03.12-dind
#  script:
#    - docker build -f implementation/txhistory/Dockerfile -t txhistory-docker .
