stages:
  - build
  - test
  - integrationTest
  - release
  - cleanup


cart_testing:
  services:
    - name: node:latest
      alias: app
  image: node:latest
  stage: test
  artifacts:
    paths:
      - implementation/cart/container/
  script:
    - cd implementation/cart/container
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test

## add services to test


integration_test:
  image: ubuntu:latest
  stage: integrationTest
  artifacts:
    paths:
      - implementation/cart/container/
  script:
    - apt-get update 
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime 
    - echo $TZ > /etc/timezone
    - apt -y install nodejs npm 
    - cd implementation/cart/container
    #install and run Java things here
    - npm start --host=app &
    - npm install -g mocha
    - npm install
    - npm run test



release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: integration_test
      artifacts: true
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'

  script:
    - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA

