
stages:
  - build
  - test
  - integrationTest
  - release
  - cleanup

create:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "${CI_JOB_ID}" > deployment/CI_JOB_ID.txt
    - ls
  artifacts:
    paths:
      - deployment



release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  #needs:
    #- job: build
      #artifacts: true
  rules:
    - if: '$RELEASE == "True"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
#    - cd deployment
    - ls
    - cd deployment
    - ls
  #  - release-cli create --name="My Release" --description="My Release description" --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA
    - |
      release-cli create --name "Release" --tag-name job-$CI_JOB_ID \
        --assets-link "{\"name\":\"Executable file\",\"url\":\"https://git01lab.cs.univie.ac.at/vu-advanced-software-engineering/students/2021s/ASE_Team_0105/-/jobs/`cat CI_JOB_ID.txt`/artifacts/CI_JOB_ID.txt\"}"
