# docker-compose.yml
version: "3"
services:
    gateway:
        build: ./implementation/gateway
        ports:
            - "8080:8080"
    checkout:
        build: ./implementation/checkout
        environment:
            - GATEWAYIP=gateway
        depends_on:
            - gateway
        ports:
            - "8086:8086"
    cart:
        build: ./implementation/cart/container
        environment:
            - GATEWAYIP=gateway
        depends_on:
            - gateway
        ports:
            - "8085:8085"   


    e2et:
        build: ./implementation/end2end_jsons
        profiles:
            - test
        depends_on:
            - cart
            - checkout
    
      
