# docker-compose.yml
version: "3"
services:
    gateway:
        build: ./implementation/gateway
        network_mode: "host"
 
    checkout:
        build: ./implementation/checkout
        network_mode: "host"
        depends_on:
            - gateway

    cart:
        build: ./implementation/cart/container
        depends_on:
            - gateway
        network_mode: "host"


    inventory:
        build: ./implementation/inventory-service
        depends_on:
            - gateway

    account-service:
        build: ./implementation/account-service
        depends_on:
            - gateway
        network_mode: "host"

    markedproduct:
        build: ./implementation/markedproduct
        depends_on:
            - gateway
        network_mode: "host"

    notification:
        build: ./implementation/notification
        depends_on:
            - gateway
        network_mode: "host"

    priceadjustment:
        build: ./implementation/priceadjustment
        depends_on:
            - gateway
        network_mode: "host"

    rating:
        build: ./implementation/rating
        depends_on:
            - gateway
        network_mode: "host"

    shipment:
        build: ./implementation/shipment
        depends_on:
            - gateway
        network_mode: "host"
    #txhistory:
    #   build: ./implementation/txhistory
    #   depends_on:
    #       - gateway
    #network_mode: "host"

    frontend:
        build: ./implementation/frontend/web
        depends_on:
            - gateway
        network_mode: "host"               


    e2et:
        build: ./implementation/end2end_jsons
        profiles:
            - test
        depends_on:
            - cart
            - checkout
        network_mode: "host"  
    
      
